spring:
  datasource:
    initialize: true
    url: jdbc:h2:~/tus
    driverClassName: org.h2.Driver
    username: sa
    password:
mybatis:
  config-location: classpath:mybatis-config.xml

tus:
  version: 1.0.0
  resumableVersion: 1.0.0
  binFilePath: ./tmp/
  infoFilePath: ./tmp/
  extensions:  creation,termination
  maxSize: 0
  loggingDir: ./tmp/log

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
server:
  port: 8080

---
spring:
  profiles: production
  h2:
    console:
      enabled: false
server:
  port:80
